spring:
  application:
    name: "SecurityService"

  profiles:
    active: "dev"

  config:
    import: "optional:configserver:http://localhost:8091"

  datasource:
    url: jdbc:postgresql://localhost:5432/securitydb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

  kafka:
    bootstrap-servers: localhost:9092